### ISSUE TITLE
Minimalist git prompt for bash blog post

### ISSUE THREAD

**Issue by sskeirik** [joshtronic/dotfiles#21]
Hey Josh,

I recently saw your blog post about the minimalist git prompt for bash/zsh; I thought it was a great idea, so I decided to use it. As you found out later, Bash needs escape codes in the `PS1` variable to be wrapped by `\[` and `\]`; this was fixed in the repo but the blog post was never updated. Since some people (such as myself) might run into the blog post first, I think it may be worth it to update it there as well.

Thanks again for sharing this here!

**Comment by joshtronic** [comment]
Thanks for the head's up on this one. Looks like I updated the blog post and forgot to respond to this issue. Cheers!
